### ISSUE TITLE
Undefined behavior when testing new features

### ISSUE THREAD

**Issue by Kaszanas** [Kaszanas/SC2InfoExtractorGo#34]
While processing on a batch of test files the following stack trace is produced:

```
unexpected fault address 0x80107ecde0
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x80107ecde0 pc=0x722b54]

goroutine 6 [running]:
runtime.throw(0xc92647, 0x5)
        D:/Programs/Go/src/runtime/panic.go:1116 +0x79 fp=0xc0000a2ab8 sp=0xc0000a2a88 pc=0x7595b9
runtime.sigpanic()
        D:/Programs/Go/src/runtime/signal_windows.go:249 +0x24f fp=0xc0000a2ae8 sp=0xc0000a2ab8 pc=0x76e0ef
memeqbody()
        D:/Programs/Go/src/internal/bytealg/equal_amd64.s:103 +0xd4 fp=0xc0000a2af0 sp=0xc0000a2ae8 pc=0x722b54
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.contains(0x10d5b40, 0x3, 0x3, 0x80107ecde0, 0x12, 0xc00f8f0000)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/utils.go:78 +0x13d fp=0xc0000a2b68 sp=0xc0000a2af0 pc=0xb89b5d
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.cleanUnusedGameEvents(0xc0000a2db0, 0xc0001c8c01)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/clean_replay.go:46 +0x18b fp=0xc0000a2c10 sp=0xc0000a2b68 pc=0xb802eb
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.extractReplayData(0xc0000ea6e0, 0xc0001c8c60, 0xc0000a3101, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/clean_replay.go:31 +0x2e7 fp=0xc0000a2ef8 sp=0xc0000a2c10 pc=0xb7ffe7
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.FileProcessingPipeline(0xc000246500, 0x71, 0x1, 0xff, 0x0, 0xc000080100, 0xc0001c8c60, 0x201, 0xc01e4a0000, 0x79744b, ...)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline.go:263 +0x5bd fp=0xc0000a3428 sp=0xc0000a2ef8 pc=0xb8335d
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.MultiprocessingChunkPipeline(0xc00001e5a0, 0x47, 0xc000248000, 0x21c, 0x400, 0x101, 0xff, 0x10000, 0xc0001c8c60, 0x8, ...)
created by github.com/Kaszanas/SC2InfoExtractorGo/dataproc.PipelineWrapper
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline.go:50 +0x1f3

goroutine 1 [semacquire, 8 minutes]:
sync.runtime_Semacquire(0xc0002a1758)
        D:/Programs/Go/src/runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc0002a1750)
        D:/Programs/Go/src/sync/waitgroup.go:130 +0x6b
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.PipelineWrapper(0xc00001e5a0, 0x47, 0xc000005560, 0x1, 0x1, 0x101, 0xff, 0x10000, 0xc0001c8c60, 0x8, ...)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline.go:80 +0x2dd
main.main()
        D:/Projects/GolangProjects/src/GoSC2Science/main.go:81 +0xa25
```

**Comment by Kaszanas** [comment]
This has never occured again even though the same dataset was processed multiple times. I am closing this.
