### ISSUE TITLE
Automatic testing for 2017 HomeStoryCup XVI FAILED

### ISSUE THREAD

**Issue by Kaszanas** [Kaszanas/SC2InfoExtractorGo#38]
While processing the tournament that is named in the title of this issue the following stack trace was produced:

```
panic: test timed out after 10m0s

goroutine 19 [running]:
testing.(*M).startAlarm.func1()
        D:/Programs/Go/src/testing/testing.go:1609 +0xe6
created by time.goFunc
        D:/Programs/Go/src/time/sleep.go:167 +0x4b

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc00006b500, 0x13d8d65, 0x1b, 0x14c1248, 0xecf801)
        D:/Programs/Go/src/testing/testing.go:1160 +0x3be
testing.runTests.func1(0xc00006b380)
        D:/Programs/Go/src/testing/testing.go:1430 +0x7f
testing.tRunner(0xc00006b380, 0xc0000afde0)
        D:/Programs/Go/src/testing/testing.go:1108 +0xef
testing.runTests(0xc0000053c0, 0x1821860, 0x2, 0x2, 0xc0507e5aaa853674, 0x8bb3069521, 0x18331a0, 0xe3e570)
        D:/Programs/Go/src/testing/testing.go:1428 +0x2eb
testing.(*M).Run(0xc0001ba200, 0x0)
        D:/Programs/Go/src/testing/testing.go:1338 +0x24e
main.main()
        _testmain.go:45 +0x145

goroutine 6 [chan receive, 3 minutes]:
testing.(*T).Run(0xc000104a80, 0xc00001b320, 0x16, 0xc0014afd40, 0x4d)
        D:/Programs/Go/src/testing/testing.go:1160 +0x3be
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.TestPipelineWrapperMultiple(0xc00006b500)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline_test.go:138 +0x23f
testing.tRunner(0xc00006b500, 0x14c1248)
        D:/Programs/Go/src/testing/testing.go:1108 +0xef
created by testing.(*T).Run
        D:/Programs/Go/src/testing/testing.go:1159 +0x397

goroutine 16 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0xc00786feb8)
        D:/Programs/Go/src/runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc00786feb0)
        D:/Programs/Go/src/sync/waitgroup.go:130 +0x6b
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.PipelineWrapper(0x13ddc8e, 0x22, 0xc0014afdc0, 0x1, 0x1, 0x101, 0x0, 0x10000, 0xc000b2d770, 0x8, ...)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline.go:83 +0x2eb
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.testPipelineWrapperWithDir(0xc0002c6780, 0x4d, 0x17dba8b, 0x25, 0xecf84d)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline_test.go:180 +0x1cb
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.TestPipelineWrapperMultiple.func1(0xc000104a80)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline_test.go:139 +0x3e
testing.tRunner(0xc000104a80, 0xc0014afd40)
        D:/Programs/Go/src/testing/testing.go:1108 +0xef
created by testing.(*T).Run
        D:/Programs/Go/src/testing/testing.go:1159 +0x397

goroutine 18 [runnable]:
reflect.makeString(0x0, 0xc031067dd8, 0x2, 0x1546720, 0x130ba20, 0xa3, 0x18, 0xc03108ac80)
        D:/Programs/Go/src/reflect/value.go:2584 +0xef
reflect.cvtBytesString(0x1302d40, 0xc03108ac80, 0x97, 0x1546720, 0x130ba20, 0x0, 0x0, 0xc00615c638)
        D:/Programs/Go/src/reflect/value.go:2668 +0xb5
reflect.Value.Convert(0x1302d40, 0xc03108ac80, 0x97, 0x1546720, 0x130ba20, 0x0, 0x1322d01, 0xc031089f60)
        D:/Programs/Go/src/reflect/value.go:2439 +0xe2
encoding/json.(*decodeState).object(0xc0310868f0, 0x12f9580, 0xc030ec2ab0, 0x16, 0xc031086918, 0x17b)
        D:/Programs/Go/src/encoding/json/decode.go:783 +0x865
encoding/json.(*decodeState).value(0xc0310868f0, 0x12f9580, 0xc030ec2ab0, 0x16, 0xc00615c988, 0xfc517f)
        D:/Programs/Go/src/encoding/json/decode.go:370 +0x79
encoding/json.(*decodeState).unmarshal(0xc0310868f0, 0x12f9580, 0xc030ec2ab0, 0xc031086918, 0x0)
        D:/Programs/Go/src/encoding/json/decode.go:180 +0x1ea
encoding/json.Unmarshal(0xc0310962d0, 0xee, 0xf0, 0x12f9580, 0xc030ec2ab0, 0xf0, 0xc03107d560)
        D:/Programs/Go/src/encoding/json/decode.go:107 +0x125
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.convertCoordinates(0xc00615cce8, 0xc000b2d770)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/convert_coordinates.go:21 +0x211
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.extractReplayData(0xc0000ec580, 0xc000b2d770, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/clean_replay.go:25 +0x12c
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.FileProcessingPipeline(0xc000316800, 0x78, 0x1, 0x0, 0x0, 0xc00c510100, 0xc000b2d770, 0x0, 0x0, 0x0, ...)       
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline.go:275 +0x5fd
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.MultiprocessingChunkPipeline(0x13ddc8e, 0x22, 0xc000312000, 0xfa, 0x100, 0x101, 0x0, 0x10000, 0xc000b2d770, 0x8, ...)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline.go:145 +0x8ab
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.PipelineWrapper.func1(0xc000400000, 0xc00786feb0, 0x13ddc8e, 0x22, 0xc000000101, 0x0, 0x1010000, 0xc000b2d770, 0x14c0008, 0x13d677f, ...)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline.go:59 +0x10c
created by github.com/Kaszanas/SC2InfoExtractorGo/dataproc.PipelineWrapper
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline.go:52 +0x205
exit status 2
FAIL    github.com/Kaszanas/SC2InfoExtractorGo/dataproc 600.544s
```

This issue requires further investigation.

**Comment by Kaszanas** [comment]
Another yet different issue that is apparent in the same tournament:

```
panic: test timed out after 10m0s

goroutine 19 [running]:
testing.(*M).startAlarm.func1()
        D:/Programs/Go/src/testing/testing.go:1609 +0xe6
created by time.goFunc
        D:/Programs/Go/src/time/sleep.go:167 +0x4b

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc00006b500, 0x1379dda, 0x1b, 0x1462310, 0xe6f801)
        D:/Programs/Go/src/testing/testing.go:1160 +0x3be
testing.runTests.func1(0xc00006b380)
        D:/Programs/Go/src/testing/testing.go:1430 +0x7f
testing.tRunner(0xc00006b380, 0xc0000afde0)
        D:/Programs/Go/src/testing/testing.go:1108 +0xef
testing.runTests(0xc000005420, 0x17c1860, 0x2, 0x2, 0xc0508fd0c85b5c90, 0x8bb3067a2d, 0x17d31a0, 0xdde570)
        D:/Programs/Go/src/testing/testing.go:1428 +0x2eb
testing.(*M).Run(0xc0001ba200, 0x0)
        D:/Programs/Go/src/testing/testing.go:1338 +0x24e
main.main()
        _testmain.go:45 +0x145

goroutine 6 [chan receive, 3 minutes]:
testing.(*T).Run(0xc0005ea300, 0xc00001b320, 0x16, 0xc0064ad320, 0x4d)
        D:/Programs/Go/src/testing/testing.go:1160 +0x3be
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.TestPipelineWrapperMultiple(0xc00006b500)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline_test.go:154 +0x250
testing.tRunner(0xc00006b500, 0x1462310)
        D:/Programs/Go/src/testing/testing.go:1108 +0xef
created by testing.(*T).Run
        D:/Programs/Go/src/testing/testing.go:1159 +0x397

goroutine 16 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0xc00ba808b8)
        D:/Programs/Go/src/runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc00ba808b0)
        D:/Programs/Go/src/sync/waitgroup.go:130 +0x6b
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.PipelineWrapper(0xc00998b340, 0x39, 0xc0060032c0, 0x1, 0x1, 0x101, 0x0, 0xc009010000, 
0xc0064ad380, 0xef0008, ...)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline.go:83 +0x2eb
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.testPipelineWrapperWithDir(0xc00001e8c0, 0x4d, 0xc00001b320, 0x16, 0x25, 0xe6f84d, 0x6161c6e6)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline_test.go:209 +0x2e9
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.TestPipelineWrapperMultiple.func1(0xc0005ea300)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline_test.go:156 +0x50
testing.tRunner(0xc0005ea300, 0xc0064ad320)
        D:/Programs/Go/src/testing/testing.go:1108 +0xef
created by testing.(*T).Run
        D:/Programs/Go/src/testing/testing.go:1159 +0x397

goroutine 18 [runnable]:
encoding/json.stringEncoder(0xc009c27180, 0x12aca00, 0xc00bb75c50, 0x98, 0xc00bb70100)
        D:/Programs/Go/src/encoding/json/encode.go:617 +0x3b9
encoding/json.(*encodeState).reflectValue(0xc009c27180, 0x12aca00, 0xc00bb75c50, 0x98, 0xc00bb70100)
        D:/Programs/Go/src/encoding/json/encode.go:358 +0x89
encoding/json.interfaceEncoder(0xc009c27180, 0x12c3dc0, 0xc018d60540, 0x94, 0xc018d60100)
        D:/Programs/Go/src/encoding/json/encode.go:714 +0xb9
encoding/json.mapEncoder.encode(0x1462100, 0xc009c27180, 0x12d0a40, 0xc002afda70, 0x15, 0x12d0100)
        D:/Programs/Go/src/encoding/json/encode.go:801 +0x37c
encoding/json.(*encodeState).reflectValue(0xc009c27180, 0x12d0a40, 0xc002afda70, 0x15, 0xc002af0100)
        D:/Programs/Go/src/encoding/json/encode.go:358 +0x89
encoding/json.interfaceEncoder(0xc009c27180, 0x12c3dc0, 0xc018d60500, 0x94, 0xc018d60100)
        D:/Programs/Go/src/encoding/json/encode.go:714 +0xb9
encoding/json.mapEncoder.encode(0x1462100, 0xc009c27180, 0x12d0a40, 0xc002afd710, 0x15, 0x12d0100)
        D:/Programs/Go/src/encoding/json/encode.go:801 +0x37c
encoding/json.(*encodeState).reflectValue(0xc009c27180, 0x12d0a40, 0xc002afd710, 0x15, 0xc002af0100)
        D:/Programs/Go/src/encoding/json/encode.go:358 +0x89
encoding/json.interfaceEncoder(0xc009c27180, 0x12c3dc0, 0xc018d604e0, 0x94, 0xc018d60100)
        D:/Programs/Go/src/encoding/json/encode.go:714 +0xb9
encoding/json.mapEncoder.encode(0x1462100, 0xc009c27180, 0x12d0a40, 0xc002afd170, 0x15, 0x12d0100)
        D:/Programs/Go/src/encoding/json/encode.go:801 +0x37c
encoding/json.(*encodeState).reflectValue(0xc009c27180, 0x12d0a40, 0xc002afd170, 0x15, 0xc002af0100)
        D:/Programs/Go/src/encoding/json/encode.go:358 +0x89
encoding/json.interfaceEncoder(0xc009c27180, 0x12c3dc0, 0xc018d603f0, 0x94, 0xc018d60100)
        D:/Programs/Go/src/encoding/json/encode.go:714 +0xb9
encoding/json.mapEncoder.encode(0x1462100, 0xc009c27180, 0x12e3dc0, 0xc032ec6d80, 0x195, 0x100)
        D:/Programs/Go/src/encoding/json/encode.go:801 +0x37c
encoding/json.arrayEncoder.encode(0xc00241e220, 0xc009c27180, 0x12a0ce0, 0xc00a58cd80, 0x197, 0x100)
        D:/Programs/Go/src/encoding/json/encode.go:886 +0xdd
encoding/json.sliceEncoder.encode(0xc00331c870, 0xc009c27180, 0x12a0ce0, 0xc00a58cd80, 0x197, 0x100)
        D:/Programs/Go/src/encoding/json/encode.go:860 +0x9c
encoding/json.structEncoder.encode(0xc00241c400, 0xb, 0x10, 0xc003b7eb70, 0xc009c27180, 0x1347f40, 0xc00a58cc80, 0x199, 0x12c0100)    
        D:/Programs/Go/src/encoding/json/encode.go:759 +0x2c3
encoding/json.ptrEncoder.encode(0xc003b7eba0, 0xc009c27180, 0x1290ba0, 0xc00a58cc80, 0x16, 0x1290100)
        D:/Programs/Go/src/encoding/json/encode.go:915 +0x125
encoding/json.(*encodeState).reflectValue(0xc009c27180, 0x1290ba0, 0xc00a58cc80, 0x16, 0xc0018b0100)
        D:/Programs/Go/src/encoding/json/encode.go:358 +0x89
encoding/json.(*encodeState).marshal(0xc009c27180, 0x1290ba0, 0xc00a58cc80, 0xc0148f0100, 0x0, 0x0)
        D:/Programs/Go/src/encoding/json/encode.go:330 +0xf7
encoding/json.Marshal(0x1290ba0, 0xc00a58cc80, 0xc0148fcb10, 0xc0148fcb40, 0xc0148fcb70, 0xc0148fcba0, 0xc0148fcbd0)
        D:/Programs/Go/src/encoding/json/encode.go:161 +0x59
encoding/json.MarshalIndent(0x1290ba0, 0xc00a58cc80, 0x0, 0x0, 0x13683b5, 0x2, 0xc0148fcbd0, 0xc0148fcc00, 0xc0148fccc0, 0xc0148fccf0, ...)
        D:/Programs/Go/src/encoding/json/encode.go:176 +0x46
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.stringifyReplay(0xc00a58cc80, 0xc0064ad301, 0xc0148fcb10, 0xc0148fcb40)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/stringify_replay.go:15 +0xd0
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.FileProcessingPipeline(0xc0000abd80, 0x78, 0x1, 0x0, 0x0, 0xc003510100, 0xc0064ad380, 
0x0, 0x0, 0x0, ...)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline.go:297 +0x6ea
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.MultiprocessingChunkPipeline(0xc00998b340, 0x39, 0xc00a5c3000, 0xfa, 0x100, 0x101, 0x0, 0x10000, 0xc0064ad380, 0x8, ...)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline.go:145 +0x8ab
github.com/Kaszanas/SC2InfoExtractorGo/dataproc.PipelineWrapper.func1(0xc00392c3c0, 0xc00ba808b0, 0xc00998b340, 0x39, 0xc000000101, 0x0, 0x1010000, 0xc0064ad380, 0x1460008, 0xc0004e0240, ...)
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline.go:59 +0x10c
created by github.com/Kaszanas/SC2InfoExtractorGo/dataproc.PipelineWrapper
        D:/Projects/GolangProjects/src/GoSC2Science/dataproc/dataproc_pipeline.go:52 +0x205
exit status 2
FAIL    github.com/Kaszanas/SC2InfoExtractorGo/dataproc 600.527s
```

**Comment by Kaszanas** [comment]
It seems that the problem is related with the default test timeout after 10 minutes

https://stackoverflow.com/questions/27778280/test-killed-with-quit-ran-too-long/31336818

https://stackoverflow.com/questions/24929790/how-to-set-the-go-timeout-flag-on-go-test
